### ISSUE TITLE
def get_agents(self) -> BaseList[Agent]: TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by RealSoerensen** [MinshuG/valorant-api#2]
I get this error using the reference code. Not sure if it is the python version I'm using or it is an error from your end.

**Comment by MinshuG** [comment]
works fine for me. can you share traceback?

**Comment by RealSoerensen** [comment]
Sorry, I don't know how to do that. I'm using Python 3.7.8 if it makes any difference

**Comment by MinshuG** [comment]
fixed
